### ISSUE TITLE
README needs description of vopher

### ISSUE THREAD

**Issue by jhillyerd** [mgumz/vopher#3]
The README would be more helpful if it included a 'What is It' section with a paragraph or two on what vopher is and why someone would want to use it.

**Comment by mgumz** [comment]
You mean something like https://github.com/mgumz/vopher#sample-session … but more obvious in the header/title section?
 
something like https://2hoch5.com/f/vopher-cast-2018-01-07.m4v ?

**Comment by jhillyerd** [comment]
(my opinion) Videos and GIFs are great, when I know what I'm looking at, but there should be some text to set the stage before that.

Ideally longer than "Acquire vim-plugins the gopher-way."  The gopher-way means [something entirely different](https://en.wikipedia.org/wiki/Gopher_(protocol)) outside of the Go community.

I think the *Why??* section of your FAQ is closer to what I was thinking...  I haven't used vopher, but maybe something like:

- Manage vim plugins without installing git
- Use `vopher fetch` to try out new plugins without modifying your vimrc
- Lock plugins to known good versions
- Easily view commit log of plugins with available updates

**Comment by mgumz** [comment]
I have added sentences at the start of the README.md. maybe over time i ll further tweak it.

Thanks for careing.
